### ISSUE TITLE
Istio not lised in the projects

### ISSUE THREAD

**Issue by kfaseela** [cncf/clotributor#506]
I cannot see [Istio](https://github.com/istio/istio) listed down in the projects list to apply as filter. Any specific reason?

https://clotributor.dev/search?page=1

**Comment by tegioz** [comment]
Hi @kfaseela 👋

In the filters we only display the projects we've been able to collect issues from. CLOTributor only indexes issues that have the `help wanted` label (in addition to some other criteria, like being open, etc). I've just checked and it looks like Istio uses `community/help wanted` instead of `help wanted`. If you could rename that label, CLOTributor should start collecting issues from Istio. Adding support for variations in this case is tricky because it'd require additional searches when indexing and we need to be very careful with GitHub API rate limits.

You can find more about information about this and some other labels that have a special meaning for CLOTributor [here](https://github.com/cncf/clotributor#how-it-works). CLOTributor feeds from the CLOMonitor data files, so if you'd like to add more repositories you can do it by [submitting a PR updating this file](https://github.com/cncf/clomonitor/blob/aa92a91caf399e1f19c89e66ec68cbe728fa3faa/data/cncf.yaml#L2814-L2830).

Hope this helps 🙂

**Comment by kfaseela** [comment]
Thanks for the inputs. Will see what can be done from our side to get integrated 🙂

**Comment by kfaseela** [comment]
@tegioz thanks for all the inputs. We created required labels, and now I can see Istio getting listed CLOTributor :)

**Comment by tegioz** [comment]
Awesome, no worries! 🙂
