### ISSUE TITLE
Feedback from ASWF

### ISSUE THREAD

**Issue by jmertic** [cncf/clotributor#557]
From @jfpanisset 

- The top level page https://clotributor.dev/ could use a few more hints as to how to search for a specific foundation, or until there are too many foundations, maybe have tiles to easily navigate to a foundation's issues? Right now just entering "aswf" in the search box doesn't find anything.
- Once you navigate to a search result, for instance https://clotributor.dev/search?foundation=aswf&page=1 it might be good to still have something in the banner for the page reminding you where you are / what the tool does?
- Don't know if this is feasible, but would be great to get some kind of stats such as how many people read an issue / commented on an issue that got to it via this tool

**Comment by JeanChristopheMorinPerso** [comment]
>Don't know if this is feasible, but would be great to get some kind of stats such as how many people read an issue / commented on an issue that got to it via this tool

Or stats on how many contributors actually found an issue via clotributor and opened a PR. I don't know if it's doable, but it would be nice.

**Comment by jmertic** [comment]
Another question that has come up is whether it could be configured to use a different tag instead of `help wanted`. Some projects have used this tag for a different purpose and are trying to see if they could avoid changing their processes. Thanks!

**Comment by tegioz** [comment]
Hi!

> * The top level page https://clotributor.dev/ could use a few more hints as to how to search for a specific foundation, or until there are too many foundations, maybe have tiles to easily navigate to a foundation's issues? Right now just entering "aswf" in the search box doesn't find anything.

The problem of adding tiles is that, as you mention, it won't work when we have more foundations. So we'd rather not to go in that direction. At the moment we are not adding the name of the foundation to the search index, that's why you can't find anything when you search by "aswf". But this is something we could improve, we'll look into it 👍

> * Once you navigate to a search result, for instance https://clotributor.dev/search?foundation=aswf&page=1 it might be good to still have something in the banner for the page reminding you where you are / what the tool does?

You can click on the CLOTributor logo to get back to the home page, where we describe what the tool does. We also include a link to the GitHub repository, where it's explained in detail how CLOTributor works. Regarding the search results, we also display the current page as well as the filters applied.

<img width="1459" alt="header" src="https://github.com/cncf/clotributor/assets/1213902/f0638685-8e17-4df6-9509-a11b2b08a39b">

> * Don't know if this is feasible, but would be great to get some kind of stats such as how many people read an issue / commented on an issue that got to it via this tool. Or stats on how many contributors actually found an issue via clotributor and opened a PR. I don't know if it's doable, but it would be nice.

We could track when an issue link is opened from CLOTributor. But once the users leaves the site we won't be able to know what they ended up doing on the GitHub side (commenting, opening a PR, etc).

> Another question that has come up is whether it could be configured to use a different tag instead of `help wanted`. Some projects have used this tag for a different purpose and are trying to see if they could avoid changing their processes.

I think we could make this configurable at the repository level (the alternative to `help wanted` would need to be set in the repository's configuration in the data file) 👍

> Thanks!

No worries!

**Comment by jmertic** [comment]
Hi @tegioz - thanks for getting back to us on this! Replies inline..

>> The top level page https://clotributor.dev/ could use a few more hints as to how to search for a specific foundation, or until there are too many foundations, maybe have tiles to easily navigate to a foundation's issues? Right now just entering "aswf" in the search box doesn't find anything.

> The problem of adding tiles is that, as you mention, it won't work when we have more foundations. So we'd rather not to go in that direction. At the moment we are not adding the name of the foundation to the search index, that's why you can't find anything when you search by "aswf". But this is something we could improve, we'll look into it 👍

I can understand the slippery slope - @jfpanisset what are your thoughts?

>> Once you navigate to a search result, for instance https://clotributor.dev/search?foundation=aswf&page=1 it might be good to still have something in the banner for the page reminding you where you are / what the tool does?

> You can click on the CLOTributor logo to get back to the home page, where we describe what the tool does. We also include a link to the GitHub repository, where it's explained in detail how CLOTributor works. Regarding the search results, we also display the current page as well as the filters applied.

@jfpanisset - what are your thoughts here?

>> Don't know if this is feasible, but would be great to get some kind of stats such as how many people read an issue / commented on an issue that got to it via this tool. Or stats on how many contributors actually found an issue via clotributor and opened a PR. I don't know if it's doable, but it would be nice.

> We could track when an issue link is opened from CLOTributor. But once the users leaves the site we won't be able to know what they ended up doing on the GitHub side (commenting, opening a PR, etc).

I think that might be at least a good step. Agreed this is a challenging problem due to cross-site tracking.

>> Another question that has come up is whether it could be configured to use a different tag instead of help wanted. Some projects have used this tag for a different purpose and are trying to see if they could avoid changing their processes.

> I think we could make this configurable at the repository level (the alternative to help wanted would need to be set in the repository's configuration in the data file) 👍

That would be great - thanks!

**Comment by tegioz** [comment]
Quick update 🙂

- We are now indexing the foundation name as part of the issues search document, which makes it possible to search by `aswf` using the search input field (#596)
- The label used to filter issues can now be configured at the repository level. So instead of `help wanted`, you could use `other-label` by setting the field shown below to the corresponding repository in the data file (#597)

```yaml
issues_filter_label: other-label
```

(please note that these changes haven't been deployed yet, we'll let you know when it's done)

Regarding tracking issues opened from CLOTributor, I've just opened another issue (#598) to track it as if we were to add some form of stats at some point, it'll be a larger change that may need additional discussion 😇

**Comment by tegioz** [comment]
The new features I mentioned yesterday have been deployed to production 🙂

**Comment by jmertic** [comment]
Thank you @tegioz !
